version: "3"

services:
  backend_blue:
    build: ./backend
    container_name: backend_blue
    networks:
      - proyecto
    expose:
      - "3000"

  backend_green:
    build: ./backend
    container_name: backend_green
    networks:
      - proyecto
    expose:
      - "3000"

  frontend_blue:
    build: ./frontend
    container_name: frontend_blue
    networks:
      - proyecto
    expose:
      - "80"

  frontend_green:
    build: ./frontend
    container_name: frontend_green
    networks:
      - proyecto
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend_blue
      - backend_green
      - frontend_blue
      - frontend_green
    networks:
      - proyecto

networks:
  proyecto:
    driver: bridge
